<?php

return [
    'date_format'               => 'd/m/Y',
    'time_format'               => 'H:i:s',
    'primary_language'          => 'en',
    'available_languages'       => [
        'en'      => 'English',
        'de'      => 'German',
        'ru'      => 'Russian',
        'fr'      => 'French',
        'es'      => 'Spanish',
        'pt-br'   => 'Brazilian Portuguese',
        'tr'      => 'Turkish',
        'ua'      => 'Ukrainian',
        'ar'      => 'Arabic',
        'pt'      => 'Portuguese',
        'sk'      => 'Slovak',
        'pl'      => 'Polish',
        'hu'      => 'Hungarian',
        'it'      => 'Italian',
        'se'      => 'Swedish',
        'gr'      => 'Greek',
        'ro'      => 'Romanian',
        'lt'      => 'Lithuanian',
        'ca'      => 'Catalan',
        'bg'      => 'Bulgarian',
        'ee'      => 'Estonian',
        'am'      => 'Armenian',
        'by'      => 'Belarusian',
        'zh-Hans' => 'Chinese',
        'cs'      => 'Czech',
        'hi'      => 'Hindi',
        'lv'      => 'Latvian',
        'dk'      => 'Danish',
    ],
    'registration_default_role' => '2',
];
